name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: copia os arquivos
        uses: actions/checkout@v3
      
      - name: instalar o python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalando o poetry
        run: pip install poetry

      - name: Instalar dependÃªncias do projeto
        run: poetry install --without doc

      - name: Rodar os testes
        run: poetry run task test --cov-report=xml

      - name: subir cobertura para o codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}